FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./

COPY prisma ./prisma/

RUN npm install

RUN npm run build

RUN npx prisma generate

COPY . .

EXPOSE 3003

CMD ["npm", "run", "start:dev"]